"""Resolve local skill directories and repositories into copied snapshots."""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import stat
import subprocess

from ..errors import SkillToPluginError
from ..models import ParsedInput, ResolvedSource
from ..utils import hash_tree, sanitize_text
from ..validation import validate_tree


def _is_link_or_reparse(path: Path) -> bool:
    metadata = path.lstat()
    return stat.S_ISLNK(metadata.st_mode) or bool(
        getattr(metadata, "st_file_attributes", 0)
        & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    )


def _normalized_boundary(path: Path) -> str:
    """Return a canonical comparison key for an existing or future path."""

    try:
        resolved = path.resolve(strict=False)
    except (OSError, RuntimeError) as exc:
        raise SkillToPluginError(
            f"Could not resolve filesystem boundary `{sanitize_text(str(path))}`.",
            code="security_rejected",
        ) from exc
    return os.path.normcase(os.path.abspath(os.fspath(resolved)))


def _contains_path(container: str, candidate: str) -> bool:
    """Compare canonical paths without relying on case-sensitive Path parts."""

    try:
        return os.path.commonpath((container, candidate)) == container
    except ValueError:
        # Different Windows drives cannot overlap.
        return False


def _reject_overlapping_copy_boundaries(source: Path, destination: Path) -> None:
    """Reject any source/destination containment before a snapshot is created.

    In particular, excluding ``destination`` from ``os.walk`` is insufficient:
    its parent output tree can already contain reports or artifacts generated by
    the current run.  A disjoint destination is therefore an invariant of local
    acquisition, including after a selected Skill is widened to its Git root.
    """

    source_boundary = _normalized_boundary(source)
    destination_boundary = _normalized_boundary(destination)
    if _contains_path(source_boundary, destination_boundary):
        raise SkillToPluginError(
            "The output snapshot is inside the local source boundary. Choose an "
            "`--output-root` outside the source repository so the snapshot cannot "
            "copy itself or include artifacts from the active conversion.",
            code="output_conflict",
            details={
                "relationship": "destination_within_source",
                "source_boundary": source_boundary,
                "snapshot_destination": destination_boundary,
            },
        )
    if _contains_path(destination_boundary, source_boundary):
        raise SkillToPluginError(
            "The local source is inside the output snapshot boundary. Source and "
            "destination must be disjoint for deterministic acquisition.",
            code="output_conflict",
            details={
                "relationship": "source_within_destination",
                "source_boundary": source_boundary,
                "snapshot_destination": destination_boundary,
            },
        )


class LocalResolver:
    @staticmethod
    def supports(parsed: ParsedInput, source_base: Path | None = None) -> bool:
        source = parsed.source or ""
        candidate = Path(os.path.expanduser(source))
        if not candidate.is_absolute() and source_base:
            candidate = source_base / candidate
        return candidate.exists()

    @staticmethod
    def _copy(source: Path, destination: Path) -> None:
        _reject_overlapping_copy_boundaries(source, destination)
        if destination.exists():
            raise SkillToPluginError(f"Snapshot destination already exists: `{destination}`.", code="output_conflict")
        destination.mkdir(parents=True)
        for current, dirnames, filenames in os.walk(source, followlinks=False):
            current_path = Path(current)
            relative = current_path.relative_to(source)
            if ".git" in relative.parts:
                dirnames.clear()
                continue
            target = destination / relative
            target.mkdir(parents=True, exist_ok=True)
            for dirname in list(dirnames):
                child = current_path / dirname
                if dirname == ".git":
                    dirnames.remove(dirname)
                    continue
                metadata = child.lstat()
                mode = metadata.st_mode
                if stat.S_ISLNK(mode) or _is_link_or_reparse(child):
                    raise SkillToPluginError(f"Symbolic links and reparse points are not allowed: `{child}`.", code="security_rejected")
                if not stat.S_ISDIR(mode):
                    raise SkillToPluginError(f"Special directory entries are not allowed: `{child}`.", code="security_rejected")
            for filename in filenames:
                child = current_path / filename
                metadata = child.lstat()
                mode = metadata.st_mode
                if _is_link_or_reparse(child) or not stat.S_ISREG(mode):
                    raise SkillToPluginError(f"Only regular files are allowed: `{child}`.", code="security_rejected")
                shutil.copy2(child, target / filename)

    @staticmethod
    def _git_metadata(path: Path) -> tuple[str | None, bool | None, Path | None]:
        git = shutil.which("git")
        if not git:
            return None, None, None
        try:
            root_result = subprocess.run(
                [git, "-C", str(path), "rev-parse", "--show-toplevel"],
                stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                text=True, encoding="utf-8", errors="replace", timeout=15, shell=False, check=False,
            )
            if root_result.returncode:
                return None, None, None
            root = Path(root_result.stdout.strip()).resolve()
            commit_result = subprocess.run(
                [git, "-C", str(root), "rev-parse", "HEAD"],
                stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                text=True, encoding="utf-8", errors="replace", timeout=15, shell=False, check=False,
            )
            dirty_result = subprocess.run(
                [git, "-C", str(root), "status", "--porcelain", "--untracked-files=normal"],
                stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                text=True, encoding="utf-8", errors="replace", timeout=15, shell=False, check=False,
            )
            commit = commit_result.stdout.strip().lower() if commit_result.returncode == 0 else None
            dirty = bool(dirty_result.stdout.strip()) if dirty_result.returncode == 0 else None
            return commit, dirty, root
        except (OSError, subprocess.TimeoutExpired):
            return None, None, None

    def resolve(self, parsed: ParsedInput, snapshot_dir: Path, *, source_base: Path) -> ResolvedSource:
        source = Path(os.path.expanduser(parsed.source or ""))
        if not source.is_absolute():
            source = source_base / source
        source = source.absolute()
        if not source.exists():
            raise SkillToPluginError(f"Local source does not exist: `{source}`.", code="unknown_source")
        try:
            if _is_link_or_reparse(source):
                raise SkillToPluginError(
                    "The local source root may not be a symbolic link or Windows reparse point.",
                    code="security_rejected",
                )
        except OSError as exc:
            raise SkillToPluginError("Could not inspect the local source root.", code="security_rejected") from exc
        source = source.resolve()
        requested_path: str | None = parsed.requested_path
        if source.is_file():
            if source.name.casefold() != "skill.md":
                raise SkillToPluginError("Only a local `SKILL.md` file can be imported directly.", code="unsupported_source")
            copy_root = source.parent
            requested_path = "SKILL.md"
        elif source.is_dir():
            copy_root = source
            if (source / "SKILL.md").is_file():
                requested_path = requested_path or "SKILL.md"
        else:
            raise SkillToPluginError("Local source is not a regular file or directory.", code="security_rejected")

        commit, dirty, git_root = self._git_metadata(copy_root)
        if parsed.metadata.get("snapshot_exact_root"):
            # Compatibility callers may already have staged the complete source
            # and require that exact directory to remain the snapshot boundary.
            git_root = None
        if git_root and git_root in [copy_root, *copy_root.parents]:
            # Preserve the exact filesystem state, including uncommitted changes,
            # but snapshot the repository root so license and plugin boundaries remain visible.
            try:
                relative = copy_root.relative_to(git_root)
                if requested_path:
                    requested_path = (relative / requested_path).as_posix()
                elif relative.parts:
                    requested_path = relative.as_posix()
                copy_root = git_root
            except ValueError:
                pass

        self._copy(copy_root, snapshot_dir)
        tree = validate_tree(snapshot_dir)
        return ResolvedSource(
            kind="local_repository" if git_root else "local_skill",
            normalized_source=str(source),
            snapshot_path=str(snapshot_dir.resolve()),
            snapshot_sha256=tree.tree_sha256,
            repository_url=None,
            requested_ref="HEAD" if commit else None,
            resolved_commit=commit,
            requested_path=requested_path,
            resolution_method="filesystem-copy",
            metadata={"git_dirty": dirty, "source_root": str(copy_root)},
        )
